apiVersion: v1
kind: Service
metadata:
  name: msfafricaapi
spec:
  selector:
    app: msfafricaapi
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msfafricaapi
spec:
  selector:
    matchLabels:
      app: msfafricaapi
  replicas: 5
  template:
    metadata:
      labels:
        app: msfafricaapi
    spec:
      containers:
      - name: msfafricaapi
        image: msfafricaapi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
