# Generated by Django 3.0.5 on 2021-07-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittedpoints', models.CharField(max_length=4000, null=True, unique=True)),
                ('closestpoints', models.CharField(max_length=4000)),
            ],
        ),
        migrations.DeleteModel(
            name='DistanceModel',
        ),
    ]
