# Generated by Django 3.0.5 on 2021-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFSApp', '0002_auto_20210728_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsmodel',
            name='submittedpoints',
            field=models.CharField(max_length=4000),
        ),
    ]
